kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: rancher/dapper:v0.4.1
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - dapper ci
  - name: run-binary
    image: rancher/dapper:v0.4.1
    commands:
      - ./bin/rke-etcd-backup --help
  - name: stage-binaries
    image: rancher/dapper:v0.4.1
    commands:
      - cp -r ./bin/* ./
    when:
      instance:
      - drone-publish.rancher.io
      refs:
      - refs/head/master
      - refs/tags/*
      event:
      - tag
  - name: publish-rke-tools-amd64
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: package/Dockerfile
      build_args:
        - ARCH=amd64
      repo: rancher/rke-tools
      tag: "${DRONE_TAG}-amd64"
    when:
      instance:
      - drone-publish.rancher.io
      refs:
      - refs/head/master
      - refs/tags/*
      event:
      - tag
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: rancher/dapper:v0.4.1
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - dapper ci
  - name: stage-binaries
    image: rancher/dapper:v0.4.1
    commands:
      - cp -r ./bin/* ./
    when:
      instance:
      - drone-publish.rancher.io
      refs:
      - refs/head/master
      - refs/tags/*
      event:
      - tag
  - name: publish-rke-tools-arm64
    image: plugins/docker:linux-arm64 
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: package/Dockerfile
      build_args:
        - ARCH=arm64
      repo: rancher/rke-tools
      tag: "${DRONE_TAG}-arm64"
    when:
      instance:
      - drone-publish.rancher.io
      refs:
      - refs/head/master
      - refs/tags/*
      event:
      - tag
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
---
kind: pipeline
name: manifest

steps:
  - name: push-manifest
    image: plugins/manifest:1.0.2
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      target: "rancher/rke-tools:${DRONE_TAG}"
      template: "rancher/rke-tools:${DRONE_TAG}-ARCH"
      platforms:
        - linux/amd64
        - linux/arm64
    when:
      instance:
      - drone-publish.rancher.io
      refs:
      - refs/head/master
      - refs/tags/*
      event:
      - tag
depends_on:
- amd64
- arm64
