---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: rancher/dapper:1.11.2
  commands:
  - dapper ci
  privileged: true
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - pull_request
    - tag

- name: stage-binaries
  image: rancher/dapper:1.11.2
  commands:
  - cp -r ./bin/* ./
  when:
    event:
    - tag

- name: publish-rke-tools
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    repo: rancher/rke-tools
    tag: ${DRONE_TAG}
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
  when:
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
