kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: rancher/dapper:v0.5.7
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - dapper ci
    when:
      refs:
      - refs/head/master
      - refs/tags/*
      event:
      - push
      - pull_request
      - tag
  - name: stage-binaries
    image: rancher/dapper:v0.5.7
    commands:
      - cp -r ./bin/* ./
    when:
      refs:
      - refs/head/master
      - refs/tags/*
      event:
      - tag
  - name: publish-rke-tools-amd64
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: package/Dockerfile
      build_args:
        - ARCH=amd64
      repo: rancher/rke-tools
      tag: "${DRONE_TAG}-linux-amd64"
      no_cache: true
    when:
      refs:
      - refs/head/master
      - refs/tags/*
      event:
      - tag
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
---
kind: pipeline
name: linux-arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: rancher/dapper:v0.5.7
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - dapper ci
    when:
      refs:
      - refs/head/master
      - refs/tags/*
      event:
      - push
      - pull_request
      - tag
  - name: stage-binaries
    image: rancher/dapper:v0.5.7
    commands:
      - cp -r ./bin/* ./
    when:
      refs:
      - refs/head/master
      - refs/tags/*
      event:
      - tag
  - name: publish-rke-tools-arm64
    image: plugins/docker:linux-arm64 
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: package/Dockerfile
      build_args:
        - ARCH=arm64
      repo: rancher/rke-tools
      tag: "${DRONE_TAG}-linux-arm64"
      no_cache: true
    when:
      refs:
      - refs/head/master
      - refs/tags/*
      event:
      - tag
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
---
kind: pipeline
name: linux-s390x

platform:
  os: linux
  arch: amd64

# Hack needed for s390x: https://gist.github.com/colstrom/c2f359f72658aaabb44150ac20b16d7c#gistcomment-3858388
node:
  arch: s390x

steps:
  - name: build
    image: rancher/dapper:v0.5.8
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - dapper ci
    when:
      refs:
      - refs/head/master
      - refs/tags/*
      event:
      - push
      - pull_request
      - tag
  - name: stage-binaries
    image: rancher/dapper:v0.5.8
    commands:
      - cp -r ./bin/* ./
    when:
      refs:
      - refs/head/master
      - refs/tags/*
      event:
      - tag
  - name: publish-rke-tools-s390x
    image: rancher/drone-images:docker-s390x
    volumes:
    - name: docker
      path: /var/run/docker.sock
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: package/Dockerfile
      build_args:
        - ARCH=s390x
      repo: rancher/rke-tools
      tag: "${DRONE_TAG}-linux-s390x"
      no_cache: true
    when:
      refs:
      - refs/head/master
      - refs/tags/*
      event:
      - tag
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
---
kind: pipeline
name: windows-1809

platform:
  os: windows
  arch: amd64
  version: 1809

steps:
  - name: publish-rke-tools-windows-1809
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: package/Dockerfile.windows
      build_args:
        - SERVERCORE_VERSION=1809
      repo: rancher/rke-tools
      tag: "${DRONE_TAG}-windows-1809"
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      refs:
      - refs/head/master
      - refs/tags/*
      event:
      - tag
volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine
---
kind: pipeline
name: windows-20H2

platform:
  os: windows
  arch: amd64
  version: 20H2

# remove this and use upstream images when https://github.com/drone/drone-git/pull/25 is merged
clone:
  disable: true

steps:
  - name: clone
    image: luthermonson/drone-git:windows-20H2-amd64
  - name: publish-rke-tools-windows-20H2
    image: luthermonson/drone-docker:20H2
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: package/Dockerfile.windows.20H2
      build_args:
        - SERVERCORE_VERSION=20H2
      repo: rancher/rke-tools
      tag: "${DRONE_TAG}-windows-20H2"
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      refs:
        - refs/head/master
        - refs/tags/*
      event:
        - tag
volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine
---
kind: pipeline
name: manifest

steps:
  - name: push-manifest
    image: plugins/manifest
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      spec: manifest.tmpl
    when:
      refs:
      - refs/head/master
      - refs/tags/*
      event:
      - tag
depends_on:
- linux-amd64
- linux-arm64
- linux-s390x
- windows-1809
- windows-20H2
