kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: rancher/dapper:v0.5.1
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - dapper ci
  - name: stage-binaries
    image: rancher/dapper:v0.5.1
    commands:
      - cp -r ./bin/* ./
    when:
      instance:
      - drone-publish.rancher.io
      refs:
      - refs/head/master
      - refs/tags/*
      event:
      - tag
  - name: publish-rke-tools-amd64
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: package/Dockerfile
      build_args:
        - ARCH=amd64
      repo: rancher/rke-tools
      tag: "${DRONE_TAG}-linux-amd64"
    when:
      instance:
      - drone-publish.rancher.io
      refs:
      - refs/head/master
      - refs/tags/*
      event:
      - tag
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
---
kind: pipeline
name: linux-arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: rancher/dapper:v0.5.1
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - dapper ci
  - name: stage-binaries
    image: rancher/dapper:v0.5.1
    commands:
      - cp -r ./bin/* ./
    when:
      instance:
      - drone-publish.rancher.io
      refs:
      - refs/head/master
      - refs/tags/*
      event:
      - tag
  - name: publish-rke-tools-arm64
    image: plugins/docker:linux-arm64 
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: package/Dockerfile
      build_args:
        - ARCH=arm64
      repo: rancher/rke-tools
      tag: "${DRONE_TAG}-linux-arm64"
    when:
      instance:
      - drone-publish.rancher.io
      refs:
      - refs/head/master
      - refs/tags/*
      event:
      - tag
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
---
kind: pipeline
name: windows-1809

platform:
  os: windows
  arch: amd64
  version: 1809

steps:
  - name: publish-rke-tools-windows-1809
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: package/Dockerfile.windows
      build_args:
        - SERVERCORE_VERSION=1809
      repo: rancher/rke-tools
      tag: "${DRONE_TAG}-windows-1809"
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      instance:
      - drone-publish.rancher.io
      refs:
      - refs/head/master
      - refs/tags/*
      event:
      - tag
volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine
---
kind: pipeline
name: windows-1903

platform:
  os: windows
  arch: amd64
  version: 1903

steps:
  - name: publish-rke-tools-windows-1903
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: package/Dockerfile.windows
      build_args:
        - SERVERCORE_VERSION=1903
      repo: rancher/rke-tools
      tag: "${DRONE_TAG}-windows-1903"
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      instance:
      - drone-publish.rancher.io
      refs:
      - refs/head/master
      - refs/tags/*
      event:
      - tag
volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine

---
kind: pipeline
name: windows-1909

platform:
  os: windows
  arch: amd64
  version: 1909

steps:
  - name: publish-rke-tools-windows-1909
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: package/Dockerfile.windows
      build_args:
        - SERVERCORE_VERSION=1909
      repo: rancher/rke-tools
      tag: "${DRONE_TAG}-windows-1909"
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      instance:
        - drone-publish.rancher.io
      refs:
        - refs/head/master
        - refs/tags/*
      event:
        - tag
volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine
---
kind: pipeline
name: windows-2004

platform:
  os: windows
  arch: amd64
  version: 2004

# remove this and use upstream images when https://github.com/drone/drone-git/pull/25 is merged
clone:
  disable: true

steps:
  - name: clone
    image: luthermonson/drone-git:windows-2004-amd64
  - name: publish-rke-tools-windows-2004
    image: luthermonson/drone-docker:2004
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: package/Dockerfile.windows
      build_args:
        - SERVERCORE_VERSION=2004
      repo: rancher/rke-tools
      tag: "${DRONE_TAG}-windows-2004"
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      instance:
        - drone-publish.rancher.io
      refs:
        - refs/head/master
        - refs/tags/*
      event:
        - tag
volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine

---
kind: pipeline
name: windows-20H2

platform:
  os: windows
  arch: amd64
  version: 20H2

# remove this and use upstream images when https://github.com/drone/drone-git/pull/25 is merged
clone:
  disable: true

steps:
  - name: clone
    image: luthermonson/drone-git:windows-20H2-amd64
  - name: publish-rke-tools-windows-20H2
    image: luthermonson/drone-docker:20H2
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: package/Dockerfile.windows
      build_args:
        - SERVERCORE_VERSION=20H2
      repo: rancher/rke-tools
      tag: "${DRONE_TAG}-windows-20H2"
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      instance:
        - drone-publish.rancher.io
      refs:
        - refs/head/master
        - refs/tags/*
      event:
        - tag
volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine
---
kind: pipeline
name: manifest

steps:
  - name: push-manifest
    image: plugins/manifest
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      spec: manifest.tmpl
    when:
      instance:
      - drone-publish.rancher.io
      refs:
      - refs/head/master
      - refs/tags/*
      event:
      - tag
depends_on:
- linux-amd64
- linux-arm64
- windows-1809
- windows-1903
- windows-1909
- windows-2004
- windows-20H2