#!/bin/bash
set -e
set -x

source $(dirname $0)/version

ARCH=${ARCH:-"amd64"}
SUFFIX="-${ARCH}"

cd $(dirname $0)/../package

TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-rancher}

if echo $TAG | grep -q dirty; then
    TAG=dev${SUFFIX}
fi

cp ../bin/rke-etcd-backup .
cp -r ../{conf.d,cert-deployer,templates,nginx-proxy,*.sh} .

IMAGE=${REPO}/rke-tools:${TAG}
docker build -t ${IMAGE} -f ${ARCH}/Dockerfile .
echo ${IMAGE} >> ../dist/images
echo Built ${IMAGE}
