#!/bin/bash
set -e

source $(dirname $0)/version

ARCH=${ARCH:-"amd64"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

cd $(dirname $0)/../package

TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-rancher}

if echo $TAG | grep -q dirty; then
    TAG=dev
fi

cp ../bin/rke-etcd-backup .
cp -r ../{conf.d,cert-deployer,templates,nginx-proxy,*.sh} .

IMAGE=${REPO}/rke-tools:${TAG}

if [ "$ARCH" == "arm64" ]; then
    docker build -f Dockerfile.arm64 -t ${IMAGE} .
else 
    docker build -t ${IMAGE} .
fi

echo ${IMAGE} > ../dist/images
echo Built ${IMAGE}
