#!/bin/bash
set -e

cd "$(dirname $0)/.."

echo Running validation

PACKAGES="$(go list ./...)"

echo Running: go vet
go vet "${PACKAGES}"

echo Running: golangci-lint
golangci-lint run --disable-all -E revive

echo Running: go fmt
test -z "$(go fmt ${PACKAGES} | tee /dev/stderr)"
