#!/bin/bash

if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
    DIRTY="-dirty"
fi

COMMIT=$(git rev-parse --short HEAD)

if [[ $GITHUB_ACTIONS = true && $GITHUB_REF_TYPE = "tag" ]]; then
    TAG_NAME=$GITHUB_REF_NAME
fi

GIT_TAG=${TAG_NAME:-$(git tag -l --contains HEAD | head -n 1)}

if [[ -z "$DIRTY" && -n "$GIT_TAG" ]]; then
    VERSION=$GIT_TAG
else
    VERSION="${COMMIT}${DIRTY}"
fi

if [ -z "$ARCH" ]; then
    ARCH=amd64
fi
